package comV2.guichetLocation;


/**
* comV2/guichetLocation/GuichetLocationPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from garage.idl
* dimanche 23 décembre 2018 17 h 49 WET
*/

public abstract class GuichetLocationPOA extends org.omg.PortableServer.Servant
 implements comV2.guichetLocation.GuichetLocationOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_l", new java.lang.Integer (0));
    _methods.put ("_set_l", new java.lang.Integer (1));
    _methods.put ("_get_voituresLoc", new java.lang.Integer (2));
    _methods.put ("_set_voituresLoc", new java.lang.Integer (3));
    _methods.put ("louer", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // comV2/guichetLocation/GuichetLocation/_get_l
       {
         int $result = (int)0;
         $result = this.l ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // comV2/guichetLocation/GuichetLocation/_set_l
       {
         int newL = in.read_long ();
         this.l (newL);
         out = $rh.createReply();
         break;
       }

       case 2:  // comV2/guichetLocation/GuichetLocation/_get_voituresLoc
       {
         comV2.Voiture $result[] = null;
         $result = this.voituresLoc ();
         out = $rh.createReply();
         comV2.VoituresListHelper.write (out, $result);
         break;
       }

       case 3:  // comV2/guichetLocation/GuichetLocation/_set_voituresLoc
       {
         comV2.Voiture newVoituresLoc[] = comV2.VoituresListHelper.read (in);
         this.voituresLoc (newVoituresLoc);
         out = $rh.createReply();
         break;
       }

       case 4:  // comV2/guichetLocation/GuichetLocation/louer
       {
         this.louer ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:comV2/guichetLocation/GuichetLocation:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GuichetLocation _this() 
  {
    return GuichetLocationHelper.narrow(
    super._this_object());
  }

  public GuichetLocation _this(org.omg.CORBA.ORB orb) 
  {
    return GuichetLocationHelper.narrow(
    super._this_object(orb));
  }


} // class GuichetLocationPOA
