package comV2.guichetLocation;


/**
* comV2/guichetLocation/GuichetLocationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from garage.idl
* dimanche 23 décembre 2018 17 h 49 WET
*/

public interface GuichetLocationOperations 
{
  int l ();
  void l (int newL);
  comV2.Voiture[] voituresLoc ();
  void voituresLoc (comV2.Voiture[] newVoituresLoc);
  void louer ();
} // interface GuichetLocationOperations
