package comV2.guichetRestitution;


/**
* comV2/guichetRestitution/GuichetRestitutionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from garage.idl
* dimanche 23 décembre 2018 17 h 49 WET
*/

abstract public class GuichetRestitutionHelper
{
  private static String  _id = "IDL:comV2/guichetRestitution/GuichetRestitution:1.0";

  public static void insert (org.omg.CORBA.Any a, comV2.guichetRestitution.GuichetRestitution that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static comV2.guichetRestitution.GuichetRestitution extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (comV2.guichetRestitution.GuichetRestitutionHelper.id (), "GuichetRestitution");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static comV2.guichetRestitution.GuichetRestitution read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GuichetRestitutionStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, comV2.guichetRestitution.GuichetRestitution value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static comV2.guichetRestitution.GuichetRestitution narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof comV2.guichetRestitution.GuichetRestitution)
      return (comV2.guichetRestitution.GuichetRestitution)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      comV2.guichetRestitution._GuichetRestitutionStub stub = new comV2.guichetRestitution._GuichetRestitutionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static comV2.guichetRestitution.GuichetRestitution unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof comV2.guichetRestitution.GuichetRestitution)
      return (comV2.guichetRestitution.GuichetRestitution)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      comV2.guichetRestitution._GuichetRestitutionStub stub = new comV2.guichetRestitution._GuichetRestitutionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
