package comV2.guichetRestitution;


/**
* comV2/guichetRestitution/GuichetRestitutionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from garage.idl
* dimanche 23 décembre 2018 17 h 49 WET
*/

public interface GuichetRestitutionOperations 
{
  int r ();
  void r (int newR);
  int nbMax ();
  comV2.Voiture[] voituresRest ();
  void voituresRest (comV2.Voiture[] newVoituresRest);
  void restituer ();
} // interface GuichetRestitutionOperations
