package comV2.guichetRestitution;

/**
* comV2/guichetRestitution/GuichetRestitutionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from garage.idl
* dimanche 23 décembre 2018 17 h 49 WET
*/

public final class GuichetRestitutionHolder implements org.omg.CORBA.portable.Streamable
{
  public comV2.guichetRestitution.GuichetRestitution value = null;

  public GuichetRestitutionHolder ()
  {
  }

  public GuichetRestitutionHolder (comV2.guichetRestitution.GuichetRestitution initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = comV2.guichetRestitution.GuichetRestitutionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    comV2.guichetRestitution.GuichetRestitutionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return comV2.guichetRestitution.GuichetRestitutionHelper.type ();
  }

}
