package comV2.guichetRestitution;


/**
* comV2/guichetRestitution/GuichetRestitution.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from garage.idl
* dimanche 23 décembre 2018 17 h 49 WET
*/

public interface GuichetRestitution extends GuichetRestitutionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GuichetRestitution
