package comV2;


/**
* comV2/Voiture.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from garage.idl
* dimanche 23 décembre 2018 17 h 49 WET
*/

public final class Voiture implements org.omg.CORBA.portable.IDLEntity
{
  public String matricule = null;
  public String marque = null;

  public Voiture ()
  {
  } // ctor

  public Voiture (String _matricule, String _marque)
  {
    matricule = _matricule;
    marque = _marque;
  } // ctor

public String getMatricule() {
	return matricule;
}

public void setMatricule(String matricule) {
	this.matricule = matricule;
}

public String getMarque() {
	return marque;
}

public void setMarque(String marque) {
	this.marque = marque;
}

@Override
public String toString() {
	return "Voiture [matricule=" + matricule + ", marque=" + marque + "]";
}

  
} // class Voiture
