package comV2;

/**
* comV2/VoitureHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from garage.idl
* dimanche 23 décembre 2018 17 h 49 WET
*/

public final class VoitureHolder implements org.omg.CORBA.portable.Streamable
{
  public comV2.Voiture value = null;

  public VoitureHolder ()
  {
  }

  public VoitureHolder (comV2.Voiture initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = comV2.VoitureHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    comV2.VoitureHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return comV2.VoitureHelper.type ();
  }

}
